name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    name: Run pre-commit hooks
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # Install dependencies
    - name: Install pre-commit and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit
        pre-commit install  # Install the git hooks

    # Run pre-commit hooks
    - name: Run pre-commit hooks
      run: pre-commit run --all-files
